/* activity.vala.c generated by valac 0.26.2, the Vala compiler
 * generated from activity.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TIMR_TYPE_ACTIVITY (timr_activity_get_type ())
#define TIMR_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_ACTIVITY, TimrActivity))
#define TIMR_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_ACTIVITY, TimrActivityClass))
#define TIMR_IS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_ACTIVITY))
#define TIMR_IS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_ACTIVITY))
#define TIMR_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_ACTIVITY, TimrActivityClass))

typedef struct _TimrActivity TimrActivity;
typedef struct _TimrActivityClass TimrActivityClass;
typedef struct _TimrActivityPrivate TimrActivityPrivate;

#define TIMR_TYPE_JOB (timr_job_get_type ())
#define TIMR_JOB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_JOB, TimrJob))
#define TIMR_JOB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_JOB, TimrJobClass))
#define TIMR_IS_JOB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_JOB))
#define TIMR_IS_JOB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_JOB))
#define TIMR_JOB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_JOB, TimrJobClass))

typedef struct _TimrJob TimrJob;
typedef struct _TimrJobClass TimrJobClass;
#define _g_time_zone_unref0(var) ((var == NULL) ? NULL : (var = (g_time_zone_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _timr_job_unref0(var) ((var == NULL) ? NULL : (var = (timr_job_unref (var), NULL)))
typedef struct _TimrParamSpecActivity TimrParamSpecActivity;

struct _TimrActivity {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TimrActivityPrivate * priv;
	gchar* description;
	TimrJob* job;
	gint job_id;
	gchar* job_name;
	gchar* client;
	gchar* type;
	gchar* text;
};

struct _TimrActivityClass {
	GTypeClass parent_class;
	void (*finalize) (TimrActivity *self);
};

struct _TimrActivityPrivate {
	GTimeZone* timezone;
	GDateTime* begin;
	GDateTime* end;
	gboolean is_running;
};

struct _TimrParamSpecActivity {
	GParamSpec parent_instance;
};


static gpointer timr_activity_parent_class = NULL;

gpointer timr_activity_ref (gpointer instance);
void timr_activity_unref (gpointer instance);
GParamSpec* timr_param_spec_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void timr_value_set_activity (GValue* value, gpointer v_object);
void timr_value_take_activity (GValue* value, gpointer v_object);
gpointer timr_value_get_activity (const GValue* value);
GType timr_activity_get_type (void) G_GNUC_CONST;
gpointer timr_job_ref (gpointer instance);
void timr_job_unref (gpointer instance);
GParamSpec* timr_param_spec_job (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void timr_value_set_job (GValue* value, gpointer v_object);
void timr_value_take_job (GValue* value, gpointer v_object);
gpointer timr_value_get_job (const GValue* value);
GType timr_job_get_type (void) G_GNUC_CONST;
#define TIMR_ACTIVITY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TIMR_TYPE_ACTIVITY, TimrActivityPrivate))
enum  {
	TIMR_ACTIVITY_DUMMY_PROPERTY
};
TimrActivity* timr_activity_new (void);
TimrActivity* timr_activity_construct (GType object_type);
TimrActivity* timr_activity_new_full (const gchar* description, TimrJob* job, GDateTime* begin, GDateTime* end);
TimrActivity* timr_activity_construct_full (GType object_type, const gchar* description, TimrJob* job, GDateTime* begin, GDateTime* end);
TimrActivity* timr_activity_new_past (const gchar* description, GDateTime* begin, GDateTime* end);
TimrActivity* timr_activity_construct_past (GType object_type, const gchar* description, GDateTime* begin, GDateTime* end);
void timr_activity_stop (TimrActivity* self);
gchar* timr_activity_get_duration_nice (TimrActivity* self);
gint timr_activity_get_duration (TimrActivity* self);
gchar* timr_activity_get_timespan_formatted (TimrActivity* self);
gchar* timr_activity_get_begin_datetime (TimrActivity* self);
gchar* timr_activity_get_end_datetime (TimrActivity* self);
gchar* timr_activity_get_date (TimrActivity* self);
GDateTime* timr_activity_get_begin (TimrActivity* self);
static void timr_activity_finalize (TimrActivity* obj);


TimrActivity* timr_activity_construct (GType object_type) {
	TimrActivity* self = NULL;
	GTimeZone* _tmp0_ = NULL;
	GTimeZone* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	self = (TimrActivity*) g_type_create_instance (object_type);
	_tmp0_ = g_time_zone_new_local ();
	_g_time_zone_unref0 (self->priv->timezone);
	self->priv->timezone = _tmp0_;
	_tmp1_ = self->priv->timezone;
	_tmp2_ = g_date_time_new_now (_tmp1_);
	_g_date_time_unref0 (self->priv->begin);
	self->priv->begin = _tmp2_;
	self->priv->is_running = TRUE;
	return self;
}


TimrActivity* timr_activity_new (void) {
	return timr_activity_construct (TIMR_TYPE_ACTIVITY);
}


static gpointer _timr_job_ref0 (gpointer self) {
	return self ? timr_job_ref (self) : NULL;
}


static gpointer _g_date_time_ref0 (gpointer self) {
	return self ? g_date_time_ref (self) : NULL;
}


TimrActivity* timr_activity_construct_full (GType object_type, const gchar* description, TimrJob* job, GDateTime* begin, GDateTime* end) {
	TimrActivity* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	TimrJob* _tmp2_ = NULL;
	TimrJob* _tmp3_ = NULL;
	GDateTime* _tmp4_ = NULL;
	GDateTime* _tmp5_ = NULL;
	GDateTime* _tmp6_ = NULL;
	GDateTime* _tmp7_ = NULL;
	g_return_val_if_fail (description != NULL, NULL);
	g_return_val_if_fail (job != NULL, NULL);
	g_return_val_if_fail (begin != NULL, NULL);
	g_return_val_if_fail (end != NULL, NULL);
	self = (TimrActivity*) g_type_create_instance (object_type);
	_tmp0_ = description;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->description);
	self->description = _tmp1_;
	_tmp2_ = job;
	_tmp3_ = _timr_job_ref0 (_tmp2_);
	_timr_job_unref0 (self->job);
	self->job = _tmp3_;
	_tmp4_ = begin;
	_tmp5_ = _g_date_time_ref0 (_tmp4_);
	_g_date_time_unref0 (self->priv->begin);
	self->priv->begin = _tmp5_;
	_tmp6_ = end;
	_tmp7_ = _g_date_time_ref0 (_tmp6_);
	_g_date_time_unref0 (self->priv->end);
	self->priv->end = _tmp7_;
	return self;
}


TimrActivity* timr_activity_new_full (const gchar* description, TimrJob* job, GDateTime* begin, GDateTime* end) {
	return timr_activity_construct_full (TIMR_TYPE_ACTIVITY, description, job, begin, end);
}


TimrActivity* timr_activity_construct_past (GType object_type, const gchar* description, GDateTime* begin, GDateTime* end) {
	TimrActivity* self = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	g_return_val_if_fail (description != NULL, NULL);
	g_return_val_if_fail (begin != NULL, NULL);
	g_return_val_if_fail (end != NULL, NULL);
	self = (TimrActivity*) g_type_create_instance (object_type);
	self->priv->is_running = FALSE;
	_tmp0_ = begin;
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
	_g_date_time_unref0 (self->priv->begin);
	self->priv->begin = _tmp1_;
	_tmp2_ = end;
	_tmp3_ = _g_date_time_ref0 (_tmp2_);
	_g_date_time_unref0 (self->priv->end);
	self->priv->end = _tmp3_;
	_tmp4_ = description;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 (self->description);
	self->description = _tmp5_;
	return self;
}


TimrActivity* timr_activity_new_past (const gchar* description, GDateTime* begin, GDateTime* end) {
	return timr_activity_construct_past (TIMR_TYPE_ACTIVITY, description, begin, end);
}


void timr_activity_stop (TimrActivity* self) {
	GTimeZone* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->timezone;
	_tmp1_ = g_date_time_new_now (_tmp0_);
	_g_date_time_unref0 (self->priv->end);
	self->priv->end = _tmp1_;
	self->priv->is_running = FALSE;
}


gchar* timr_activity_get_duration_nice (TimrActivity* self) {
	gchar* result = NULL;
	gchar* duration_nice = NULL;
	gint duration = 0;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GTimeSpan _tmp2_ = 0LL;
	gint hours = 0;
	gint _tmp3_ = 0;
	gint minutes = 0;
	gint _tmp4_ = 0;
	gint seconds = 0;
	gint _tmp5_ = 0;
	gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	const gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	const gchar* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->end;
	_tmp1_ = self->priv->begin;
	_tmp2_ = g_date_time_difference (_tmp0_, _tmp1_);
	duration = ((gint) _tmp2_) / 1000000;
	_tmp3_ = duration;
	hours = _tmp3_ / 3600;
	_tmp4_ = duration;
	minutes = (_tmp4_ / 60) % 60;
	_tmp5_ = duration;
	seconds = _tmp5_ % 60;
	_tmp7_ = hours;
	if (_tmp7_ > 0) {
		gint _tmp8_ = 0;
		gchar* _tmp9_ = NULL;
		_tmp8_ = hours;
		_tmp9_ = g_strdup_printf ("<b>%02u</b>", (guint) _tmp8_);
		_g_free0 (_tmp6_);
		_tmp6_ = _tmp9_;
	} else {
		gint _tmp10_ = 0;
		gchar* _tmp11_ = NULL;
		_tmp10_ = hours;
		_tmp11_ = g_strdup_printf ("%02u", (guint) _tmp10_);
		_g_free0 (_tmp6_);
		_tmp6_ = _tmp11_;
	}
	_tmp12_ = g_strdup (_tmp6_);
	_g_free0 (duration_nice);
	duration_nice = _tmp12_;
	_tmp13_ = duration_nice;
	_tmp14_ = g_strconcat (_tmp13_, ":", NULL);
	_g_free0 (duration_nice);
	duration_nice = _tmp14_;
	_tmp16_ = minutes;
	if (_tmp16_ > 0) {
		gint _tmp17_ = 0;
		gchar* _tmp18_ = NULL;
		_tmp17_ = minutes;
		_tmp18_ = g_strdup_printf ("<b>%02u</b>", (guint) _tmp17_);
		_g_free0 (_tmp15_);
		_tmp15_ = _tmp18_;
	} else {
		gint _tmp19_ = 0;
		gchar* _tmp20_ = NULL;
		_tmp19_ = minutes;
		_tmp20_ = g_strdup_printf ("%02u", (guint) _tmp19_);
		_g_free0 (_tmp15_);
		_tmp15_ = _tmp20_;
	}
	_tmp21_ = duration_nice;
	_tmp22_ = g_strconcat (_tmp21_, _tmp15_, NULL);
	_g_free0 (duration_nice);
	duration_nice = _tmp22_;
	_tmp23_ = duration_nice;
	_tmp24_ = g_strconcat (_tmp23_, ":", NULL);
	_g_free0 (duration_nice);
	duration_nice = _tmp24_;
	_tmp25_ = duration_nice;
	_tmp26_ = seconds;
	_tmp27_ = g_strdup_printf ("%02u", (guint) _tmp26_);
	_tmp28_ = _tmp27_;
	_tmp29_ = g_strconcat (_tmp25_, _tmp28_, NULL);
	_g_free0 (duration_nice);
	duration_nice = _tmp29_;
	_g_free0 (_tmp28_);
	result = duration_nice;
	_g_free0 (_tmp15_);
	_g_free0 (_tmp6_);
	return result;
}


gint timr_activity_get_duration (TimrActivity* self) {
	gint result = 0;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GTimeSpan _tmp2_ = 0LL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->end;
	_tmp1_ = self->priv->begin;
	_tmp2_ = g_date_time_difference (_tmp0_, _tmp1_);
	result = ((gint) _tmp2_) / 1000000;
	return result;
}


gchar* timr_activity_get_timespan_formatted (TimrActivity* self) {
	gchar* result = NULL;
	gchar* timespan = NULL;
	GDateTime* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->begin;
	_tmp1_ = g_date_time_format (_tmp0_, "%H:%M");
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->end;
	_tmp4_ = g_date_time_format (_tmp3_, "%H:%M");
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strdup_printf ("%s - %s", _tmp2_, _tmp5_);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	timespan = _tmp7_;
	result = timespan;
	return result;
}


gchar* timr_activity_get_begin_datetime (TimrActivity* self) {
	gchar* result = NULL;
	GDateTime* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->begin;
	_tmp1_ = g_date_time_format (_tmp0_, "%Y-%m-%d %T");
	result = _tmp1_;
	return result;
}


gchar* timr_activity_get_end_datetime (TimrActivity* self) {
	gchar* result = NULL;
	GDateTime* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->end;
	_tmp1_ = g_date_time_format (_tmp0_, "%Y-%m-%d %T");
	result = _tmp1_;
	return result;
}


gchar* timr_activity_get_date (TimrActivity* self) {
	gchar* result = NULL;
	GDateTime* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->begin;
	_tmp1_ = g_date_time_format (_tmp0_, "%Y-%m-%d");
	result = _tmp1_;
	return result;
}


GDateTime* timr_activity_get_begin (TimrActivity* self) {
	GDateTime* result = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->begin;
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static void timr_value_activity_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void timr_value_activity_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		timr_activity_unref (value->data[0].v_pointer);
	}
}


static void timr_value_activity_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = timr_activity_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer timr_value_activity_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* timr_value_activity_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TimrActivity* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = timr_activity_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* timr_value_activity_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TimrActivity** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = timr_activity_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* timr_param_spec_activity (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TimrParamSpecActivity* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TIMR_TYPE_ACTIVITY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer timr_value_get_activity (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_ACTIVITY), NULL);
	return value->data[0].v_pointer;
}


void timr_value_set_activity (GValue* value, gpointer v_object) {
	TimrActivity* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_ACTIVITY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_ACTIVITY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		timr_activity_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_activity_unref (old);
	}
}


void timr_value_take_activity (GValue* value, gpointer v_object) {
	TimrActivity* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_ACTIVITY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_ACTIVITY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_activity_unref (old);
	}
}


static void timr_activity_class_init (TimrActivityClass * klass) {
	timr_activity_parent_class = g_type_class_peek_parent (klass);
	((TimrActivityClass *) klass)->finalize = timr_activity_finalize;
	g_type_class_add_private (klass, sizeof (TimrActivityPrivate));
}


static void timr_activity_instance_init (TimrActivity * self) {
	self->priv = TIMR_ACTIVITY_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void timr_activity_finalize (TimrActivity* obj) {
	TimrActivity * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TIMR_TYPE_ACTIVITY, TimrActivity);
	g_signal_handlers_destroy (self);
	_g_time_zone_unref0 (self->priv->timezone);
	_g_date_time_unref0 (self->priv->begin);
	_g_date_time_unref0 (self->priv->end);
	_g_free0 (self->description);
	_timr_job_unref0 (self->job);
	_g_free0 (self->job_name);
	_g_free0 (self->client);
	_g_free0 (self->type);
	_g_free0 (self->text);
}


GType timr_activity_get_type (void) {
	static volatile gsize timr_activity_type_id__volatile = 0;
	if (g_once_init_enter (&timr_activity_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { timr_value_activity_init, timr_value_activity_free_value, timr_value_activity_copy_value, timr_value_activity_peek_pointer, "p", timr_value_activity_collect_value, "p", timr_value_activity_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TimrActivityClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) timr_activity_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TimrActivity), 0, (GInstanceInitFunc) timr_activity_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType timr_activity_type_id;
		timr_activity_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TimrActivity", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&timr_activity_type_id__volatile, timr_activity_type_id);
	}
	return timr_activity_type_id__volatile;
}


gpointer timr_activity_ref (gpointer instance) {
	TimrActivity* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void timr_activity_unref (gpointer instance) {
	TimrActivity* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TIMR_ACTIVITY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



