/* activity_dialog.vala.c generated by valac 0.26.2, the Vala compiler
 * generated from activity_dialog.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TIMR_TYPE_ACTIVITY_DIALOG (timr_activity_dialog_get_type ())
#define TIMR_ACTIVITY_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_ACTIVITY_DIALOG, TimrActivityDialog))
#define TIMR_ACTIVITY_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_ACTIVITY_DIALOG, TimrActivityDialogClass))
#define TIMR_IS_ACTIVITY_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_ACTIVITY_DIALOG))
#define TIMR_IS_ACTIVITY_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_ACTIVITY_DIALOG))
#define TIMR_ACTIVITY_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_ACTIVITY_DIALOG, TimrActivityDialogClass))

typedef struct _TimrActivityDialog TimrActivityDialog;
typedef struct _TimrActivityDialogClass TimrActivityDialogClass;
typedef struct _TimrActivityDialogPrivate TimrActivityDialogPrivate;

#define TIMR_TYPE_APPLICATION_WINDOW (timr_application_window_get_type ())
#define TIMR_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_APPLICATION_WINDOW, TimrApplicationWindow))
#define TIMR_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_APPLICATION_WINDOW, TimrApplicationWindowClass))
#define TIMR_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_APPLICATION_WINDOW))
#define TIMR_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_APPLICATION_WINDOW))
#define TIMR_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_APPLICATION_WINDOW, TimrApplicationWindowClass))

typedef struct _TimrApplicationWindow TimrApplicationWindow;
typedef struct _TimrApplicationWindowClass TimrApplicationWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _TimrActivityDialog {
	GtkDialog parent_instance;
	TimrActivityDialogPrivate * priv;
};

struct _TimrActivityDialogClass {
	GtkDialogClass parent_class;
};

struct _TimrActivityDialogPrivate {
	GtkEntry* description_entry;
	GtkComboBox* job_combobox;
	GtkCalendar* calendar;
	GtkEntry* timespan_entry;
	GDateTime* begin;
	GDateTime* end;
	gint job_id;
	gchar* job_name;
	gchar* text;
	gchar* job_abbrev;
	gchar* job_display_name;
	TimrApplicationWindow* parent_window;
};


static gpointer timr_activity_dialog_parent_class = NULL;

GType timr_activity_dialog_get_type (void) G_GNUC_CONST;
GType timr_application_window_get_type (void) G_GNUC_CONST;
#define TIMR_ACTIVITY_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TIMR_TYPE_ACTIVITY_DIALOG, TimrActivityDialogPrivate))
enum  {
	TIMR_ACTIVITY_DIALOG_DUMMY_PROPERTY
};
TimrActivityDialog* timr_activity_dialog_new (TimrApplicationWindow* window, GtkTreeStore* clients_jobs);
TimrActivityDialog* timr_activity_dialog_construct (GType object_type, TimrApplicationWindow* window, GtkTreeStore* clients_jobs);
static void timr_activity_dialog_split_time (TimrActivityDialog* self, const gchar* str, gint* hours, gint* minutes);
static gboolean timr_activity_dialog_split_timespan (TimrActivityDialog* self);
void timr_application_window_error (TimrApplicationWindow* self, const gchar* message);
GDateTime* timr_activity_dialog_get_begin (TimrActivityDialog* self);
GDateTime* timr_activity_dialog_get_end (TimrActivityDialog* self);
gchar* timr_activity_dialog_get_description (TimrActivityDialog* self);
static void timr_activity_dialog_get_job_detail (TimrActivityDialog* self);
gint timr_activity_dialog_get_job_id (TimrActivityDialog* self);
gchar* timr_activity_dialog_get_text (TimrActivityDialog* self);
gchar* timr_activity_dialog_get_job_display_name (TimrActivityDialog* self);
gchar* timr_activity_dialog_get_job_name (TimrActivityDialog* self);
gchar* timr_activity_dialog_get_job_abbrev (TimrActivityDialog* self);
static void timr_activity_dialog_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


TimrActivityDialog* timr_activity_dialog_construct (GType object_type, TimrApplicationWindow* window, GtkTreeStore* clients_jobs) {
	TimrActivityDialog * self = NULL;
	TimrApplicationWindow* _tmp0_ = NULL;
	GtkComboBox* _tmp1_ = NULL;
	GtkTreeStore* _tmp2_ = NULL;
	g_return_val_if_fail (window != NULL, NULL);
	g_return_val_if_fail (clients_jobs != NULL, NULL);
	_tmp0_ = window;
	self = (TimrActivityDialog*) g_object_new (object_type, "transient-for", _tmp0_, "use-header-bar", 0, NULL);
	_tmp1_ = self->priv->job_combobox;
	_tmp2_ = clients_jobs;
	gtk_combo_box_set_model (_tmp1_, (GtkTreeModel*) _tmp2_);
	return self;
}


TimrActivityDialog* timr_activity_dialog_new (TimrApplicationWindow* window, GtkTreeStore* clients_jobs) {
	return timr_activity_dialog_construct (TIMR_TYPE_ACTIVITY_DIALOG, window, clients_jobs);
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static void timr_activity_dialog_split_time (TimrActivityDialog* self, const gchar* str, gint* hours, gint* minutes) {
	gint _vala_hours = 0;
	gint _vala_minutes = 0;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (str != NULL);
	_vala_minutes = 0;
	_tmp0_ = _vala_minutes;
	_vala_hours = _tmp0_;
	_tmp1_ = str;
	_tmp2_ = strlen (_tmp1_);
	_tmp3_ = _tmp2_;
	switch (_tmp3_) {
		case 1:
		case 2:
		{
			const gchar* _tmp4_ = NULL;
			gint _tmp5_ = 0;
			_tmp4_ = str;
			_tmp5_ = atoi (_tmp4_);
			_vala_hours = _tmp5_;
			_vala_minutes = 0;
			break;
		}
		case 3:
		{
			const gchar* _tmp6_ = NULL;
			gchar* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			const gchar* _tmp10_ = NULL;
			gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			_tmp6_ = str;
			_tmp7_ = string_substring (_tmp6_, (glong) 0, (glong) 2);
			_tmp8_ = _tmp7_;
			_tmp9_ = atoi (_tmp8_);
			_vala_hours = _tmp9_;
			_g_free0 (_tmp8_);
			_tmp10_ = str;
			_tmp11_ = string_substring (_tmp10_, (glong) 2, (glong) 1);
			_tmp12_ = _tmp11_;
			_tmp13_ = atoi (_tmp12_);
			_vala_minutes = _tmp13_ * 10;
			_g_free0 (_tmp12_);
			break;
		}
		case 4:
		{
			const gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			gint _tmp17_ = 0;
			const gchar* _tmp18_ = NULL;
			gchar* _tmp19_ = NULL;
			gchar* _tmp20_ = NULL;
			gint _tmp21_ = 0;
			_tmp14_ = str;
			_tmp15_ = string_substring (_tmp14_, (glong) 0, (glong) 2);
			_tmp16_ = _tmp15_;
			_tmp17_ = atoi (_tmp16_);
			_vala_hours = _tmp17_;
			_g_free0 (_tmp16_);
			_tmp18_ = str;
			_tmp19_ = string_substring (_tmp18_, (glong) 2, (glong) 2);
			_tmp20_ = _tmp19_;
			_tmp21_ = atoi (_tmp20_);
			_vala_minutes = _tmp21_;
			_g_free0 (_tmp20_);
			break;
		}
		default:
		break;
	}
	if (hours) {
		*hours = _vala_hours;
	}
	if (minutes) {
		*minutes = _vala_minutes;
	}
}


static gboolean timr_activity_dialog_split_timespan (TimrActivityDialog* self) {
	gboolean result = FALSE;
	guint year = 0U;
	guint month = 0U;
	guint day = 0U;
	guint hours = 0U;
	guint minutes = 0U;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	year = (guint) 1915;
	month = (guint) 0;
	day = (guint) 1;
	hours = (guint) 0;
	minutes = (guint) 0;
	{
		GtkCalendar* _tmp0_ = NULL;
		guint _tmp1_ = 0U;
		guint _tmp2_ = 0U;
		guint _tmp3_ = 0U;
		gchar* timespan = NULL;
		GtkEntry* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		GRegex* regex = NULL;
		GRegex* _tmp7_ = NULL;
		gchar* _timespan = NULL;
		GRegex* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		gchar* _tmp13_ = NULL;
		gchar** times = NULL;
		const gchar* _tmp14_ = NULL;
		gchar** _tmp15_ = NULL;
		gchar** _tmp16_ = NULL;
		gint times_length1 = 0;
		gint _times_size_ = 0;
		gchar** _tmp17_ = NULL;
		gint _tmp17__length1 = 0;
		_tmp0_ = self->priv->calendar;
		gtk_calendar_get_date (_tmp0_, &_tmp1_, &_tmp2_, &_tmp3_);
		year = _tmp1_;
		month = _tmp2_;
		day = _tmp3_;
		_tmp4_ = self->priv->timespan_entry;
		_tmp5_ = gtk_entry_get_text (_tmp4_);
		_tmp6_ = g_strdup (_tmp5_);
		timespan = _tmp6_;
		_tmp7_ = g_regex_new ("[^0-9\\-]", 0, 0, &_inner_error_);
		regex = _tmp7_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_free0 (timespan);
			goto __catch0_g_error;
		}
		_tmp8_ = regex;
		_tmp9_ = timespan;
		_tmp10_ = timespan;
		_tmp11_ = strlen (_tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_regex_replace (_tmp8_, _tmp9_, (gssize) _tmp12_, 0, "", 0, &_inner_error_);
		_timespan = _tmp13_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			_g_free0 (timespan);
			goto __catch0_g_error;
		}
		_tmp14_ = _timespan;
		_tmp16_ = _tmp15_ = g_regex_split_simple ("(.+)\\-(.+)", _tmp14_, 0, 0);
		times = _tmp16_;
		times_length1 = _vala_array_length (_tmp15_);
		_times_size_ = times_length1;
		_tmp17_ = times;
		_tmp17__length1 = times_length1;
		if (_tmp17__length1 > 2) {
			gchar** _tmp18_ = NULL;
			gint _tmp18__length1 = 0;
			const gchar* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			guint _tmp22_ = 0U;
			guint _tmp23_ = 0U;
			guint _tmp24_ = 0U;
			guint _tmp25_ = 0U;
			guint _tmp26_ = 0U;
			GDateTime* _tmp27_ = NULL;
			gchar** _tmp28_ = NULL;
			gint _tmp28__length1 = 0;
			const gchar* _tmp29_ = NULL;
			gint _tmp30_ = 0;
			gint _tmp31_ = 0;
			guint _tmp32_ = 0U;
			guint _tmp33_ = 0U;
			guint _tmp34_ = 0U;
			guint _tmp35_ = 0U;
			guint _tmp36_ = 0U;
			GDateTime* _tmp37_ = NULL;
			_tmp18_ = times;
			_tmp18__length1 = times_length1;
			_tmp19_ = _tmp18_[1];
			timr_activity_dialog_split_time (self, _tmp19_, &_tmp20_, &_tmp21_);
			hours = (guint) _tmp20_;
			minutes = (guint) _tmp21_;
			_tmp22_ = year;
			_tmp23_ = month;
			_tmp24_ = day;
			_tmp25_ = hours;
			_tmp26_ = minutes;
			_tmp27_ = g_date_time_new_local ((gint) _tmp22_, (gint) _tmp23_, (gint) _tmp24_, (gint) _tmp25_, (gint) _tmp26_, (gdouble) 0);
			_g_date_time_unref0 (self->priv->begin);
			self->priv->begin = _tmp27_;
			_tmp28_ = times;
			_tmp28__length1 = times_length1;
			_tmp29_ = _tmp28_[2];
			timr_activity_dialog_split_time (self, _tmp29_, &_tmp30_, &_tmp31_);
			hours = (guint) _tmp30_;
			minutes = (guint) _tmp31_;
			_tmp32_ = year;
			_tmp33_ = month;
			_tmp34_ = day;
			_tmp35_ = hours;
			_tmp36_ = minutes;
			_tmp37_ = g_date_time_new_local ((gint) _tmp32_, (gint) _tmp33_, (gint) _tmp34_, (gint) _tmp35_, (gint) _tmp36_, (gdouble) 0);
			_g_date_time_unref0 (self->priv->end);
			self->priv->end = _tmp37_;
		} else {
			result = FALSE;
			times = (_vala_array_free (times, times_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (_timespan);
			_g_regex_unref0 (regex);
			_g_free0 (timespan);
			return result;
		}
		times = (_vala_array_free (times, times_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (_timespan);
		_g_regex_unref0 (regex);
		_g_free0 (timespan);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		TimrApplicationWindow* _tmp38_ = NULL;
		GError* _tmp39_ = NULL;
		const gchar* _tmp40_ = NULL;
		gchar* _tmp41_ = NULL;
		gchar* _tmp42_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp38_ = self->priv->parent_window;
		_tmp39_ = e;
		_tmp40_ = _tmp39_->message;
		_tmp41_ = g_strconcat ("Error: ", _tmp40_, NULL);
		_tmp42_ = _tmp41_;
		timr_application_window_error (_tmp38_, _tmp42_);
		_g_free0 (_tmp42_);
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = TRUE;
	return result;
}


static gchar* g_date_time_to_string (GDateTime* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_date_time_format (self, "%FT%H:%M:%S%z");
	result = _tmp0_;
	return result;
}


static gpointer _g_date_time_ref0 (gpointer self) {
	return self ? g_date_time_ref (self) : NULL;
}


GDateTime* timr_activity_dialog_get_begin (TimrActivityDialog* self) {
	GDateTime* result = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GDateTime* _tmp4_ = NULL;
	GDateTime* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->begin;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_split_timespan (self);
	}
	_tmp1_ = self->priv->begin;
	_tmp2_ = g_date_time_to_string (_tmp1_);
	_tmp3_ = _tmp2_;
	g_debug ("activity_dialog.vala:97: %s\n", _tmp3_);
	_g_free0 (_tmp3_);
	_tmp4_ = self->priv->begin;
	_tmp5_ = _g_date_time_ref0 (_tmp4_);
	result = _tmp5_;
	return result;
}


GDateTime* timr_activity_dialog_get_end (TimrActivityDialog* self) {
	GDateTime* result = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GDateTime* _tmp4_ = NULL;
	GDateTime* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->end;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_split_timespan (self);
	}
	_tmp1_ = self->priv->end;
	_tmp2_ = g_date_time_to_string (_tmp1_);
	_tmp3_ = _tmp2_;
	g_debug ("activity_dialog.vala:105: %s\n", _tmp3_);
	_g_free0 (_tmp3_);
	_tmp4_ = self->priv->end;
	_tmp5_ = _g_date_time_ref0 (_tmp4_);
	result = _tmp5_;
	return result;
}


gchar* timr_activity_dialog_get_description (TimrActivityDialog* self) {
	gchar* result = NULL;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->description_entry;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void timr_activity_dialog_get_job_detail (TimrActivityDialog* self) {
	GtkTreeIter iter = {0};
	GtkTreeStore* model = NULL;
	GtkComboBox* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GtkTreeStore* _tmp2_ = NULL;
	gint job_id = 0;
	gchar* job_name = NULL;
	gchar* job_abbrev = NULL;
	gchar* job_display_name = NULL;
	GtkComboBox* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	gboolean _tmp5_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->job_combobox;
	_tmp1_ = gtk_combo_box_get_model (_tmp0_);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_tree_store_get_type (), GtkTreeStore));
	model = _tmp2_;
	_tmp3_ = self->priv->job_combobox;
	_tmp5_ = gtk_combo_box_get_active_iter (_tmp3_, &_tmp4_);
	iter = _tmp4_;
	if (_tmp5_) {
		GtkTreeStore* _tmp6_ = NULL;
		GtkTreeIter _tmp7_ = {0};
		gint _tmp8_ = 0;
		_tmp6_ = model;
		_tmp7_ = iter;
		_tmp8_ = gtk_tree_store_iter_depth (_tmp6_, &_tmp7_);
		if (_tmp8_ > 0) {
			GtkTreeStore* _tmp9_ = NULL;
			GtkTreeIter _tmp10_ = {0};
			gint _tmp11_ = 0;
			const gchar* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			gchar* _tmp17_ = NULL;
			gchar* _tmp18_ = NULL;
			GtkEntry* _tmp19_ = NULL;
			const gchar* _tmp20_ = NULL;
			gchar* _tmp21_ = NULL;
			const gchar* _tmp22_ = NULL;
			gchar* _tmp23_ = NULL;
			const gchar* _tmp24_ = NULL;
			gchar* _tmp25_ = NULL;
			_tmp9_ = model;
			_tmp10_ = iter;
			gtk_tree_model_get ((GtkTreeModel*) _tmp9_, &_tmp10_, 0, &job_id, 1, &job_name, 2, &job_abbrev, 3, &job_display_name, -1);
			_tmp11_ = job_id;
			self->priv->job_id = _tmp11_;
			_tmp12_ = job_display_name;
			_tmp13_ = g_strdup (_tmp12_);
			_g_free0 (self->priv->job_name);
			self->priv->job_name = _tmp13_;
			_tmp14_ = job_display_name;
			_tmp15_ = g_strconcat ("<b>", _tmp14_, NULL);
			_tmp16_ = _tmp15_;
			_tmp17_ = g_strconcat (_tmp16_, "</b>\n", NULL);
			_tmp18_ = _tmp17_;
			_tmp19_ = self->priv->description_entry;
			_tmp20_ = gtk_entry_get_text (_tmp19_);
			_tmp21_ = g_strconcat (_tmp18_, _tmp20_, NULL);
			_g_free0 (self->priv->text);
			self->priv->text = _tmp21_;
			_g_free0 (_tmp18_);
			_g_free0 (_tmp16_);
			_tmp22_ = job_abbrev;
			_tmp23_ = g_strdup (_tmp22_);
			_g_free0 (self->priv->job_abbrev);
			self->priv->job_abbrev = _tmp23_;
			_tmp24_ = job_display_name;
			_tmp25_ = g_strdup (_tmp24_);
			_g_free0 (self->priv->job_display_name);
			self->priv->job_display_name = _tmp25_;
		}
	}
	_g_free0 (job_display_name);
	_g_free0 (job_abbrev);
	_g_free0 (job_name);
	_g_object_unref0 (model);
}


gint timr_activity_dialog_get_job_id (TimrActivityDialog* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->job_id;
	if (_tmp0_ == 0) {
		timr_activity_dialog_get_job_detail (self);
	}
	_tmp1_ = self->priv->job_id;
	result = _tmp1_;
	return result;
}


gchar* timr_activity_dialog_get_text (TimrActivityDialog* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->text;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_get_job_detail (self);
	}
	_tmp1_ = self->priv->text;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


gchar* timr_activity_dialog_get_job_display_name (TimrActivityDialog* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->job_display_name;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_get_job_detail (self);
	}
	_tmp1_ = self->priv->job_display_name;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


gchar* timr_activity_dialog_get_job_name (TimrActivityDialog* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->job_name;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_get_job_detail (self);
	}
	_tmp1_ = self->priv->job_name;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


gchar* timr_activity_dialog_get_job_abbrev (TimrActivityDialog* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->job_abbrev;
	if (_tmp0_ == NULL) {
		timr_activity_dialog_get_job_detail (self);
	}
	_tmp1_ = self->priv->job_abbrev;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


static void timr_activity_dialog_class_init (TimrActivityDialogClass * klass) {
	gint TimrActivityDialog_private_offset;
	timr_activity_dialog_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TimrActivityDialogPrivate));
	G_OBJECT_CLASS (klass)->finalize = timr_activity_dialog_finalize;
	TimrActivityDialog_private_offset = g_type_class_get_instance_private_offset (klass);
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/de/hannenz/timr/activity_dialog.ui");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "description_entry", FALSE, TimrActivityDialog_private_offset + G_STRUCT_OFFSET (TimrActivityDialogPrivate, description_entry));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "job_combobox", FALSE, TimrActivityDialog_private_offset + G_STRUCT_OFFSET (TimrActivityDialogPrivate, job_combobox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "calendar", FALSE, TimrActivityDialog_private_offset + G_STRUCT_OFFSET (TimrActivityDialogPrivate, calendar));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "timespan_entry", FALSE, TimrActivityDialog_private_offset + G_STRUCT_OFFSET (TimrActivityDialogPrivate, timespan_entry));
}


static void timr_activity_dialog_instance_init (TimrActivityDialog * self) {
	self->priv = TIMR_ACTIVITY_DIALOG_GET_PRIVATE (self);
	self->priv->begin = NULL;
	self->priv->end = NULL;
	self->priv->job_id = 0;
	self->priv->job_name = NULL;
	self->priv->text = NULL;
	self->priv->job_abbrev = NULL;
	self->priv->job_display_name = NULL;
	gtk_widget_init_template (GTK_WIDGET (self));
}


static void timr_activity_dialog_finalize (GObject* obj) {
	TimrActivityDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TIMR_TYPE_ACTIVITY_DIALOG, TimrActivityDialog);
	_g_object_unref0 (self->priv->description_entry);
	_g_object_unref0 (self->priv->job_combobox);
	_g_object_unref0 (self->priv->calendar);
	_g_object_unref0 (self->priv->timespan_entry);
	_g_date_time_unref0 (self->priv->begin);
	_g_date_time_unref0 (self->priv->end);
	_g_free0 (self->priv->job_name);
	_g_free0 (self->priv->text);
	_g_free0 (self->priv->job_abbrev);
	_g_free0 (self->priv->job_display_name);
	_g_object_unref0 (self->priv->parent_window);
	G_OBJECT_CLASS (timr_activity_dialog_parent_class)->finalize (obj);
}


GType timr_activity_dialog_get_type (void) {
	static volatile gsize timr_activity_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&timr_activity_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TimrActivityDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) timr_activity_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TimrActivityDialog), 0, (GInstanceInitFunc) timr_activity_dialog_instance_init, NULL };
		GType timr_activity_dialog_type_id;
		timr_activity_dialog_type_id = g_type_register_static (gtk_dialog_get_type (), "TimrActivityDialog", &g_define_type_info, 0);
		g_once_init_leave (&timr_activity_dialog_type_id__volatile, timr_activity_dialog_type_id);
	}
	return timr_activity_dialog_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



