/* client.vala.c generated by valac 0.26.2, the Vala compiler
 * generated from client.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TIMR_TYPE_CLIENT (timr_client_get_type ())
#define TIMR_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_CLIENT, TimrClient))
#define TIMR_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_CLIENT, TimrClientClass))
#define TIMR_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_CLIENT))
#define TIMR_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_CLIENT))
#define TIMR_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_CLIENT, TimrClientClass))

typedef struct _TimrClient TimrClient;
typedef struct _TimrClientClass TimrClientClass;
typedef struct _TimrClientPrivate TimrClientPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _TimrParamSpecClient TimrParamSpecClient;

struct _TimrClient {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TimrClientPrivate * priv;
};

struct _TimrClientClass {
	GTypeClass parent_class;
	void (*finalize) (TimrClient *self);
};

struct _TimrClientPrivate {
	gint id;
	gchar* name;
	gchar* abbrev;
};

struct _TimrParamSpecClient {
	GParamSpec parent_instance;
};


static gpointer timr_client_parent_class = NULL;

gpointer timr_client_ref (gpointer instance);
void timr_client_unref (gpointer instance);
GParamSpec* timr_param_spec_client (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void timr_value_set_client (GValue* value, gpointer v_object);
void timr_value_take_client (GValue* value, gpointer v_object);
gpointer timr_value_get_client (const GValue* value);
GType timr_client_get_type (void) G_GNUC_CONST;
#define TIMR_CLIENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TIMR_TYPE_CLIENT, TimrClientPrivate))
enum  {
	TIMR_CLIENT_DUMMY_PROPERTY
};
TimrClient* timr_client_new (gint id, const gchar* name, const gchar* abbrev);
TimrClient* timr_client_construct (GType object_type, gint id, const gchar* name, const gchar* abbrev);
gint timr_client_get_id (TimrClient* self);
gchar* timr_client_get_name (TimrClient* self);
void timr_client_set_name (TimrClient* self, const gchar* name);
gchar* timr_client_get_abbrev (TimrClient* self);
void timr_client_set_abbrev (TimrClient* self, const gchar* abbrev);
static void timr_client_finalize (TimrClient* obj);


TimrClient* timr_client_construct (GType object_type, gint id, const gchar* name, const gchar* abbrev) {
	TimrClient* self = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (TimrClient*) g_type_create_instance (object_type);
	_tmp0_ = id;
	self->priv->id = _tmp0_;
	_tmp1_ = name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp2_;
	_tmp3_ = abbrev;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (self->priv->abbrev);
	self->priv->abbrev = _tmp4_;
	return self;
}


TimrClient* timr_client_new (gint id, const gchar* name, const gchar* abbrev) {
	return timr_client_construct (TIMR_TYPE_CLIENT, id, name, abbrev);
}


gint timr_client_get_id (TimrClient* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->id;
	result = _tmp0_;
	return result;
}


gchar* timr_client_get_name (TimrClient* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->name;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


void timr_client_set_name (TimrClient* self, const gchar* name) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp1_;
}


gchar* timr_client_get_abbrev (TimrClient* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->abbrev;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


void timr_client_set_abbrev (TimrClient* self, const gchar* abbrev) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (abbrev != NULL);
	_tmp0_ = abbrev;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->abbrev);
	self->priv->abbrev = _tmp1_;
}


static void timr_value_client_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void timr_value_client_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		timr_client_unref (value->data[0].v_pointer);
	}
}


static void timr_value_client_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = timr_client_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer timr_value_client_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* timr_value_client_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TimrClient* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = timr_client_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* timr_value_client_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TimrClient** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = timr_client_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* timr_param_spec_client (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TimrParamSpecClient* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TIMR_TYPE_CLIENT), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer timr_value_get_client (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_CLIENT), NULL);
	return value->data[0].v_pointer;
}


void timr_value_set_client (GValue* value, gpointer v_object) {
	TimrClient* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_CLIENT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_CLIENT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		timr_client_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_client_unref (old);
	}
}


void timr_value_take_client (GValue* value, gpointer v_object) {
	TimrClient* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_CLIENT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_CLIENT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_client_unref (old);
	}
}


static void timr_client_class_init (TimrClientClass * klass) {
	timr_client_parent_class = g_type_class_peek_parent (klass);
	((TimrClientClass *) klass)->finalize = timr_client_finalize;
	g_type_class_add_private (klass, sizeof (TimrClientPrivate));
}


static void timr_client_instance_init (TimrClient * self) {
	self->priv = TIMR_CLIENT_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void timr_client_finalize (TimrClient* obj) {
	TimrClient * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TIMR_TYPE_CLIENT, TimrClient);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->name);
	_g_free0 (self->priv->abbrev);
}


GType timr_client_get_type (void) {
	static volatile gsize timr_client_type_id__volatile = 0;
	if (g_once_init_enter (&timr_client_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { timr_value_client_init, timr_value_client_free_value, timr_value_client_copy_value, timr_value_client_peek_pointer, "p", timr_value_client_collect_value, "p", timr_value_client_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TimrClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) timr_client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TimrClient), 0, (GInstanceInitFunc) timr_client_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType timr_client_type_id;
		timr_client_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TimrClient", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&timr_client_type_id__volatile, timr_client_type_id);
	}
	return timr_client_type_id__volatile;
}


gpointer timr_client_ref (gpointer instance) {
	TimrClient* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void timr_client_unref (gpointer instance) {
	TimrClient* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TIMR_CLIENT_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



