/* job.vala.c generated by valac 0.26.2, the Vala compiler
 * generated from job.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TIMR_TYPE_JOB (timr_job_get_type ())
#define TIMR_JOB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_JOB, TimrJob))
#define TIMR_JOB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_JOB, TimrJobClass))
#define TIMR_IS_JOB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_JOB))
#define TIMR_IS_JOB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_JOB))
#define TIMR_JOB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_JOB, TimrJobClass))

typedef struct _TimrJob TimrJob;
typedef struct _TimrJobClass TimrJobClass;
typedef struct _TimrJobPrivate TimrJobPrivate;

#define TIMR_TYPE_CLIENT (timr_client_get_type ())
#define TIMR_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TIMR_TYPE_CLIENT, TimrClient))
#define TIMR_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TIMR_TYPE_CLIENT, TimrClientClass))
#define TIMR_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TIMR_TYPE_CLIENT))
#define TIMR_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TIMR_TYPE_CLIENT))
#define TIMR_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TIMR_TYPE_CLIENT, TimrClientClass))

typedef struct _TimrClient TimrClient;
typedef struct _TimrClientClass TimrClientClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _timr_client_unref0(var) ((var == NULL) ? NULL : (var = (timr_client_unref (var), NULL)))
typedef struct _TimrParamSpecJob TimrParamSpecJob;

struct _TimrJob {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TimrJobPrivate * priv;
};

struct _TimrJobClass {
	GTypeClass parent_class;
	void (*finalize) (TimrJob *self);
};

struct _TimrJobPrivate {
	gint id;
	gchar* name;
	gchar* abbrev;
	TimrClient* client;
};

struct _TimrParamSpecJob {
	GParamSpec parent_instance;
};


static gpointer timr_job_parent_class = NULL;

gpointer timr_job_ref (gpointer instance);
void timr_job_unref (gpointer instance);
GParamSpec* timr_param_spec_job (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void timr_value_set_job (GValue* value, gpointer v_object);
void timr_value_take_job (GValue* value, gpointer v_object);
gpointer timr_value_get_job (const GValue* value);
GType timr_job_get_type (void) G_GNUC_CONST;
gpointer timr_client_ref (gpointer instance);
void timr_client_unref (gpointer instance);
GParamSpec* timr_param_spec_client (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void timr_value_set_client (GValue* value, gpointer v_object);
void timr_value_take_client (GValue* value, gpointer v_object);
gpointer timr_value_get_client (const GValue* value);
GType timr_client_get_type (void) G_GNUC_CONST;
#define TIMR_JOB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TIMR_TYPE_JOB, TimrJobPrivate))
enum  {
	TIMR_JOB_DUMMY_PROPERTY
};
TimrJob* timr_job_new (gint id, const gchar* name, const gchar* abbrev, TimrClient* client);
TimrJob* timr_job_construct (GType object_type, gint id, const gchar* name, const gchar* abbrev, TimrClient* client);
gint timr_job_get_id (TimrJob* self);
void timr_job_set_id (TimrJob* self, gint id);
gchar* timr_job_get_name (TimrJob* self);
void timr_job_set_name (TimrJob* self, const gchar* name);
gchar* timr_job_get_abbrev (TimrJob* self);
void timr_job_set_abbrev (TimrJob* self, const gchar* abbrev);
TimrClient* timr_job_get_client (TimrJob* self);
void timr_job_set_client (TimrJob* self, TimrClient* client);
static void timr_job_finalize (TimrJob* obj);


static gpointer _timr_client_ref0 (gpointer self) {
	return self ? timr_client_ref (self) : NULL;
}


TimrJob* timr_job_construct (GType object_type, gint id, const gchar* name, const gchar* abbrev, TimrClient* client) {
	TimrJob* self = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	TimrClient* _tmp5_ = NULL;
	TimrClient* _tmp6_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (abbrev != NULL, NULL);
	g_return_val_if_fail (client != NULL, NULL);
	self = (TimrJob*) g_type_create_instance (object_type);
	_tmp0_ = id;
	self->priv->id = _tmp0_;
	_tmp1_ = name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp2_;
	_tmp3_ = abbrev;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (self->priv->abbrev);
	self->priv->abbrev = _tmp4_;
	_tmp5_ = client;
	_tmp6_ = _timr_client_ref0 (_tmp5_);
	_timr_client_unref0 (self->priv->client);
	self->priv->client = _tmp6_;
	return self;
}


TimrJob* timr_job_new (gint id, const gchar* name, const gchar* abbrev, TimrClient* client) {
	return timr_job_construct (TIMR_TYPE_JOB, id, name, abbrev, client);
}


gint timr_job_get_id (TimrJob* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->id;
	result = _tmp0_;
	return result;
}


void timr_job_set_id (TimrJob* self, gint id) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = id;
	self->priv->id = _tmp0_;
}


gchar* timr_job_get_name (TimrJob* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->name;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


void timr_job_set_name (TimrJob* self, const gchar* name) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->name);
	self->priv->name = _tmp1_;
}


gchar* timr_job_get_abbrev (TimrJob* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->abbrev;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


void timr_job_set_abbrev (TimrJob* self, const gchar* abbrev) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (abbrev != NULL);
	_tmp0_ = abbrev;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->abbrev);
	self->priv->abbrev = _tmp1_;
}


TimrClient* timr_job_get_client (TimrJob* self) {
	TimrClient* result = NULL;
	TimrClient* _tmp0_ = NULL;
	TimrClient* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->client;
	_tmp1_ = _timr_client_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


void timr_job_set_client (TimrJob* self, TimrClient* client) {
	TimrClient* _tmp0_ = NULL;
	TimrClient* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (client != NULL);
	_tmp0_ = client;
	_tmp1_ = _timr_client_ref0 (_tmp0_);
	_timr_client_unref0 (self->priv->client);
	self->priv->client = _tmp1_;
}


static void timr_value_job_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void timr_value_job_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		timr_job_unref (value->data[0].v_pointer);
	}
}


static void timr_value_job_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = timr_job_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer timr_value_job_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* timr_value_job_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TimrJob* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = timr_job_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* timr_value_job_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TimrJob** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = timr_job_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* timr_param_spec_job (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TimrParamSpecJob* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TIMR_TYPE_JOB), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer timr_value_get_job (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_JOB), NULL);
	return value->data[0].v_pointer;
}


void timr_value_set_job (GValue* value, gpointer v_object) {
	TimrJob* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_JOB));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_JOB));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		timr_job_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_job_unref (old);
	}
}


void timr_value_take_job (GValue* value, gpointer v_object) {
	TimrJob* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TIMR_TYPE_JOB));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TIMR_TYPE_JOB));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		timr_job_unref (old);
	}
}


static void timr_job_class_init (TimrJobClass * klass) {
	timr_job_parent_class = g_type_class_peek_parent (klass);
	((TimrJobClass *) klass)->finalize = timr_job_finalize;
	g_type_class_add_private (klass, sizeof (TimrJobPrivate));
}


static void timr_job_instance_init (TimrJob * self) {
	self->priv = TIMR_JOB_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void timr_job_finalize (TimrJob* obj) {
	TimrJob * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TIMR_TYPE_JOB, TimrJob);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->name);
	_g_free0 (self->priv->abbrev);
	_timr_client_unref0 (self->priv->client);
}


GType timr_job_get_type (void) {
	static volatile gsize timr_job_type_id__volatile = 0;
	if (g_once_init_enter (&timr_job_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { timr_value_job_init, timr_value_job_free_value, timr_value_job_copy_value, timr_value_job_peek_pointer, "p", timr_value_job_collect_value, "p", timr_value_job_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TimrJobClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) timr_job_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TimrJob), 0, (GInstanceInitFunc) timr_job_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType timr_job_type_id;
		timr_job_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TimrJob", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&timr_job_type_id__volatile, timr_job_type_id);
	}
	return timr_job_type_id__volatile;
}


gpointer timr_job_ref (gpointer instance) {
	TimrJob* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void timr_job_unref (gpointer instance) {
	TimrJob* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TIMR_JOB_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



